/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import Hammer from "./game/Hammer"
import FloatScore from "./game/FloatScore"
import GameManager from "./game/GameManager"
import Mouse from "./game/Mouse"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=960;
    static height:number=640;
    static scaleMode:string="fixedheight";
    static screenMode:string="horizontal";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="Main.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("game/Hammer.ts",Hammer);
        reg("game/FloatScore.ts",FloatScore);
        reg("game/GameManager.ts",GameManager);
        reg("game/Mouse.ts",Mouse);
    }
}
GameConfig.init();